# Generated by Django 5.1.1 on 2024-10-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='eamil',
            new_name='email',
        ),
    ]
